site_name: Machine Learning Experiment Infrastructure
site_url: https://roberttlange.github.io/mle-infrastructure/
site_description: 'Remote ML experiments with Google Cloud Storage logging.'
site_author: Robert Tjarko Lange

repo_name: 'RobertTLange/mle-toolbox'
repo_url: 'https://github.com/RobertTLange/mle-toolbox'

copyright: Copyright &copy; 2021 - Robert Tjarko Lange

theme:
  name: material
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
  favicon: thumbnails/favicon.ico
  logo: thumbnails/favicon.png

# plugins:
#  - mkdocs-jupyter

nav:
  - Home: index.md
  - Logging:
    - logging/mle_logging.md
  - HyperOpt:
    - hyperopt/mle_hyperopt.md
  - Monitor:
    - monitor/mle_monitor.md
  - Toolbox:
    - toolbox/mle_toolbox.md
    - toolbox/mle_run.md
    - toolbox/mle_retrieve.md
    - toolbox/mle_report.md
    - toolbox/mle_sync_gcs.md
    - toolbox/mle_monitor.md
    - toolbox/mle_init.md
    - toolbox/experiments.md
  - Getting Started:
    - setup/installation.md
    - setup/configuration.md
    - setup/template.md
    - setup/video_tutorials.md


markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/roberttlange
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/roberttlange
