site_name: Machine Learning Experiment Toolbox
site_url: https://roberttlange.github.io/mle-toolbox/
site_description: 'Remote ML experiments with Google Cloud Storage logging.'
site_author: Robert Tjarko Lange

repo_name: 'RobertTLange/mle-toolbox'
repo_url: 'https://github.com/RobertTLange/mle-toolbox'

copyright: Copyright &copy; 2021 - Robert Tjarko Lange

theme:
  name: material
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
  favicon: thumbnails/favicon.ico
  logo: thumbnails/favicon.png

plugins:
 - mkdocs-jupyter

nav:
  - Home: index.md
  - Getting Started:
    - setup/installation.md
    - setup/configuration.md
    - setup/template.md
    - setup/video_tutorials.md
  - Core API:
    - core_api/mle_run.md
    - core_api/mle_retrieve.md
    - core_api/mle_report.md
    - core_api/mle_sync_gcs.md
    - core_api/mle_monitor.md
    - core_api/mle_init.md
  - Experiments:
    - experiment_types/single_pre_post.md
    - experiment_types/multiple_configs.md
    - experiment_types/hyperparameter_search.md
    - experiment_types/population_based_training.md
  - MLE Logger:
    - logging/mle_logging.md
  - MLE Hyperopt:
    - hyperopt/mle_hyperopt.md
  #- Examples: examples.md
  - Development:
    - dev/infrastructure.md
    - dev/remote_backends.md
    - dev/testing.md
    - dev/notes.md
    - dev/future_plans.md


markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/roberttlange
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/roberttlange
