train_config:
  lrate: 1e-06
  num_gd_steps: 400

log_config:
  time_to_track: ["num_steps"]
  what_to_track: ["loss"]
  verbose: true
  print_every_k_updates: 1
  log_every_j_steps: 1
  overwrite: 1
