# Meta Arguments: What job? What train .py file? Base config? Where to store?
meta_job_args:
    project_name: "examples"
    experiment_type: "multiple-experiments"
    base_train_fname: "mnist/run_mnist_network.py"
    base_train_config: "mnist/mnist_cnn_config.json"
    experiment_dir: "experiments/mnist_configs"

# Parameters specific to the experiment type
multi_config_args:
    config_fnames:
        - "mnist_mlp_config.json"
        - "mnist_cnn_config.json"
    num_seeds: 2

# Parameters specific to an individual job
single_job_args:
    job_name: "cnn"
    num_gpus: 1
    num_logical_cores: 2
    log_file: "log-cnn"
    err_file: "error-cnn"
    env_name: "mle-toolbox"
    # Days:Hours:Minutes
    time_per_job: "00:00:30"
