# Meta Arguments: What job? What train .py file? Base config? Where to store?
meta_job_args:
    project_name: "examples"
    job_type: "multiple-experiments"
    base_train_fname: "bash_configs/parse_input.sh"
    base_train_config: "bash_configs/bash_config_1.json"
    experiment_dir: "experiments/bash"
    remote_exec_dir: "mle-toolbox/examples/"

multi_config_args:
    config_fnames:
        - "bash_configs/bash_config_1.json"
        - "bash_configs/bash_config_2.json"
    num_seeds: 5


# Parameters specific to an individual job
single_job_args:
    job_name: "ode"
    num_logical_cores: 2
    log_file: "l-bash"
    err_file: "e-bash"
    env_name: "mle-toolbox"
    extra_cmd_line_input:
        random_in: 10
