
name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests on ${{ matrix.os }} with Python ${{ matrix.python }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python: ['3.7', '3.8', '3.9']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install testing and linting dependencies
      run: |
        make install-dev
    - name: Format with black style
      run: |
        make format
    - name: Lint with flake8
      run: |
        make lint
    - name: Type-check with MyPy
      run: |
        make type-check
    - name: Run unit tests
      run: |
        make test-unit
    - name: Run integration tests
      run: |
        make test-integration
