  
name: Python tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests on ${{ matrix.os }} with Python ${{ matrix.python }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python: ['3.8']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install testing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-timeout
    - name: Install requirements
      run: |
        if [ -f requirements/requirements.txt ]; then pip install -r requirements/requirements.txt; fi
        pip install --no-cache-dir git+https://github.com/mapillary/inplace_abn.git@v1.0.12
    - name: Run tests
      run: |
        pytest -vv --durations=0 ./tests/unit
